export const Competence = [
  {
    children: [
      {
        always_show: null,
        component: () => import("/src/views/track/harvest.vue"),
        hidden: false,
        icon: "document",
        id: 21,
        igrade: 21,
        keep_alive: true,
        meta: {
          title: "收货查询",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "收货查询",
        parent_id: 21,
        path: "harvest",
        title: "收货查询",
      },
      {
        always_show: null,
        component: () => import("/src/views/track/rejection.vue"),
        hidden: false,
        icon: "document",
        id:22,
        igrade: 22,
        keep_alive: true,
        meta: {
          title: "拒收查询",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "拒收查询",
        parent_id:22,
        path: "rejection",
        title: "拒收查询",
      },
      {
        always_show: null,
        component: () => import("/src/views/track/deposit.vue"),
        hidden: false,
        icon: "document",
        id:23,
        igrade: 23,
        keep_alive: true,
        meta: {
          title: "入库查询",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "入库查询",
        parent_id:23,
        path: "deposit",
        title: "入库查询",
      },
      {
        always_show: null,
        component: () => import("/src/views/track/retreat.vue"),
        hidden: false,
        icon: "document",
        id:24,
        igrade: 24,
        keep_alive: true,
        meta: {
          title: "退货查询",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "退货查询",
        parent_id:24,
        path: "retreat",
        title: "退货查询",
      },
      {
        always_show: null,
        component: () => import("/src/views/track/redOutbound.vue"),
        hidden: false,
        icon: "document",
        id:24,
        igrade: 24,
        keep_alive: true,
        meta: {
          title: "红字材料出库单查询",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "红字材料出库单查询",
        parent_id:24,
        path: "redOutbound",
        title: "红字材料出库单查询",
      },
    ],
    component: () => import("/src/layout/index.vue"),
    hidden: false,
    meta: {
      hidden: false,
      icon: "document",
      roles: ["ROOT", "ADMIN", "vendor"],
      title: "发货跟踪",
    },
    icon: "setting",
    id: 20,
    name: "发货跟踪",
    path: "/track",
    parent_id: 20,
    keep_alive: null,
    igrade: 20,
  },
  {
    children: [
      {
        always_show: null,
        component: () => import("/src/views/purchase/notice.vue"),
        hidden: false,
        icon: "document",
        id: 31,
        igrade: 31,
        keep_alive: true,
        meta: {
          title: "开票通知单",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "开票通知单",
        parent_id: 31,
        path: "notice",
        title: "开票通知单",
      },
      {
        always_show: null,
        component: () => import("/src/views/purchase/detailed.vue"),
        hidden: false,
        icon: "document",
        id:32,
        igrade: 32,
        keep_alive: true,
        meta: {
          title: "开票明细",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "开票明细",
        parent_id:32,
        path: "detailed",
        title: "开票明细",
      },
      {
        always_show: null,
        component: () => import("/src/views/purchase/tobeconfirmed.vue"),
        hidden: false,
        icon: "document",
        id:33,
        igrade: 33,
        keep_alive: true,
        meta: {
          title: "入库查询",
          icon: "document",
          hidden: false,
          roles: [],
        },
        name: "入库查询",
        parent_id:33,
        path: "tobeconfirmed",
        title: "入库查询",
      },
   
    ],
    component: () => import("/src/layout/index.vue"),
    hidden: false,
    meta: {
      hidden: false,
      icon: "document",
      roles: ["ROOT", "ADMIN", "vendor"],
      title: "采购开票",
    },
    icon: "setting",
    id: 30,
    name: "采购开票",
    path: "/purchase",
    parent_id: 30,
    keep_alive: null,
    igrade: 30,
  },
];
