export const Competence = {
  children: [
    {
      always_show: null,
      component: () => import("/src/views/system/role/index.vue"),
      hidden: false,
      icon: "document",
      id: 7,
      igrade: 7,
      keep_alive: true,
      meta: {
        title: "角色管理",
        icon: "document",
        hidden: false,
        roles: [],
      },
      name: "角色管理",
      parent_id: 7,
      path: "role",
      title: "角色管理",
    },
    {
      always_show: null,
      component: () => import("/src/views/system/menu/index.vue"),
      hidden: false,
      icon: "document",
      id: 7,
      igrade: 7,
      keep_alive: true,
      meta: {
        title: "权限管理",
        icon: "document",
        hidden: false,
        roles: [],
      },
      name: "权限管理",
      parent_id: 7,
      path: "menu",
      title: "权限管理",
    },
  ],
  component: () => import("/src/layout/index.vue"),
  hidden: false,
  meta: {
    hidden: false,
    icon: "document",
    roles: ["ROOT", "ADMIN", "vendor"],
    title: "系统管理",
  },
  icon: "setting",
  id: 6,
  name: "系统管理",
  path: "/system",
  parent_id: 6,
  keep_alive: null,
  igrade: 2,
};
